# Generated by Django 4.0.4 on 2022-08-27 06:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_email_alter_user_special_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 6, 51, 13, 144958, tzinfo=utc), verbose_name='کاربر ویژه تا'),
        ),
    ]
