# Generated by Django 4.0 on 2022-02-07 12:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CateGory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='عنوان دسته بندی در url')),
                ('status', models.BooleanField(default=True, verbose_name='این دسته بندی  نمایش داده شوند؟')),
                ('position', models.IntegerField(verbose_name='پوزیشن')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='عنوان در url')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='image_post', verbose_name='تصویر')),
                ('published', models.DateTimeField(default=datetime.datetime(2022, 2, 7, 12, 59, 19, 422828, tzinfo=utc), verbose_name='زمان انتشار')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='اخرین به روز رسانی')),
                ('status', models.CharField(choices=[('d', ' پیش نویس'), ('p', 'منتشر شده')], max_length=1, verbose_name='وضعیت')),
                ('category', models.ManyToManyField(related_name='post_category', to='blog.CateGory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
                'ordering': ['-published'],
            },
        ),
    ]
