# Generated by Django 4.0 on 2022-02-07 12:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 7, 12, 59, 50, 293594, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
