# Generated by Django 4.0 on 2022-02-07 13:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_post',
            field=models.IntegerField(blank=True, default=1, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 7, 13, 2, 14, 120820, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
