# Generated by Django 4.0.4 on 2022-07-25 12:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_is_special_alter_post_published_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='مقاله ویژه'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 25, 12, 46, 37, 256096, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
