# Generated by Django 4.0.4 on 2022-04-13 12:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_parent_alter_post_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default.png', upload_to='category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.category', verbose_name='والد'),
        ),
        migrations.AlterField(
            model_name='post',
            name='number_post',
            field=models.IntegerField(blank=True, default=1, null=True, unique=True, verbose_name='شماره پست'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 13, 12, 32, 52, 75651, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
