# Generated by Django 4.0.4 on 2022-04-13 12:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_image_alter_category_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category/default.png', upload_to='category', verbose_name='تصویر دسته بندی'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 13, 12, 41, 7, 967014, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
