# Generated by Django 4.0.4 on 2022-09-08 12:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_ipaddress_alter_post_published_time_post_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 8, 12, 25, 45, 739354, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
