# Generated by Django 4.0.4 on 2022-09-08 13:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_published_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'verbose_name': 'ی پی آدرس کاربران', 'verbose_name_plural': 'آی پی آدرس کاربران'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='hits',
        ),
        migrations.AlterField(
            model_name='post',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 8, 13, 18, 5, 938963, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
