# Generated by Django 4.0.4 on 2022-04-13 14:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_category_options_post_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_time'], 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='published',
        ),
        migrations.AddField(
            model_name='post',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 13, 14, 53, 28, 176168, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
