# Generated by Django 4.0.4 on 2022-09-08 13:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_ipaddress_options_remove_post_hits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ipaddress', verbose_name='آی پی آدرس')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', through='blog.PostHit', to='blog.ipaddress'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 8, 13, 22, 24, 575756, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
        migrations.AddField(
            model_name='posthit',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='مقاله'),
        ),
    ]
