# Generated by Django 4.0.4 on 2022-09-09 13:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_posthit_post_hits_alter_post_published_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hits',
            field=models.ManyToManyField(blank=True, null=True, related_name='hits', through='blog.PostHit', to='blog.ipaddress'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 9, 13, 18, 55, 15089, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
