# Generated by Django 4.0.4 on 2022-09-27 11:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_hits_alter_post_published_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 11, 54, 33, 71605, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts_slider', models.ManyToManyField(blank=True, null=True, related_name='slider_p', to='blog.post', verbose_name='پست های اسلایدر')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر',
            },
        ),
    ]
