# Generated by Django 4.0.4 on 2022-04-24 10:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_published_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 24, 10, 3, 54, 292835, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
