# Generated by Django 4.0.4 on 2022-09-27 11:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_published_time_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.CharField(default='slider', max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 11, 59, 36, 288948, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='posts_slider',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='slider_p', to='blog.post', verbose_name='پست های اسلایدر'),
        ),
    ]
