# Generated by Django 4.0.4 on 2022-09-27 12:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_slider_active_alter_post_published_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 12, 7, 56, 698570, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='active',
            field=models.BooleanField(default=False, verbose_name='اسلایدر فعال'),
        ),
    ]
