# Generated by Django 4.0.4 on 2022-09-27 12:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_post_published_time_alter_slider_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0, verbose_name='تعداد پسندها'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 12, 47, 57, 197871, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
