# Generated by Django 4.0.4 on 2022-10-03 12:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_post_like_post_like_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 12, 49, 36, 765867, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='خبر', max_length=200, verbose_name='عنوان')),
                ('post', models.ManyToManyField(related_name='tag_post', to='blog.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'هشتگ',
                'verbose_name_plural': 'هشتگ ها',
            },
        ),
    ]
