# Generated by Django 4.0.4 on 2022-10-03 12:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_post_published_time_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 12, 53, 44, 641045, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
