# Generated by Django 4.0.4 on 2022-10-03 13:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_post_published_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='slug',
            field=models.SlugField(default='news', max_length=100, unique=True, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 13, 13, 51, 375066, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
