# Generated by Django 4.0.4 on 2022-10-03 13:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_post_published_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 13, 52, 57, 989285, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
        migrations.CreateModel(
            name='TagHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ipaddress', verbose_name='آی پی آدرس')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.hashtag', verbose_name='برچسب')),
            ],
        ),
    ]
