# Generated by Django 4.0.4 on 2022-10-03 13:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_post_published_time_taghit'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='hits',
            field=models.ManyToManyField(blank=True, null=True, related_name='tag_hit', through='blog.TagHit', to='blog.ipaddress'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 13, 54, 8, 655327, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
