# Generated by Django 4.0.4 on 2022-10-05 19:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_post_published_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 5, 19, 21, 49, 211605, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
