# Generated by Django 4.0.4 on 2022-10-07 09:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_alter_post_published_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 7, 9, 57, 15, 437466, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
